package com.example.offlineshapealarm.challenge
import android.Manifest; import android.app.Activity; import android.content.*; import android.content.pm.PackageManager; import android.net.Uri; import android.os.Build; import android.provider.MediaStore; import android.provider.Settings; import androidx.core.content.FileProvider; import com.facebook.react.bridge.*; import com.facebook.react.modules.core.PermissionAwareActivity; import com.facebook.react.modules.core.PermissionListener; import java.io.File
class ShapeCameraChallengeModule(private val ctx: ReactApplicationContext): ReactContextBaseJavaModule(ctx), ActivityEventListener, PermissionListener { private var permissionPromise:Promise?=null; private var capturePromise:Promise?=null; private var outputFile:File?=null; private var target="elongated"; private var difficulty="normal"; init{ ctx.addActivityEventListener(this) }; override fun getName()="ShapeCameraChallenge"
 @ReactMethod fun getCameraPermissionStatus(promise:Promise){ promise.resolve(status()) }
 @ReactMethod fun requestCameraPermission(promise:Promise){ if(Build.VERSION.SDK_INT<23){ promise.resolve("granted"); return }; val a=currentActivity as? PermissionAwareActivity ?: run{ promise.resolve(status()); return }; permissionPromise=promise; a.requestPermissions(arrayOf(Manifest.permission.CAMERA), 8844, this) }
 @ReactMethod fun captureAndAnalyze(targetShapeId:String, difficulty:String, promise:Promise){ if(status()!="granted"){ promise.reject("CAMERA_PERMISSION_DENIED","Camera permission is required."); return }; val activity=currentActivity ?: run{ promise.reject("CAMERA_UNAVAILABLE","No active Android activity."); return }; val dir=File(ctx.cacheDir,"challenge-images").apply{mkdirs()}; val file=File.createTempFile("challenge-", ".jpg", dir); outputFile=file; target=targetShapeId; this.difficulty=difficulty; capturePromise=promise; val uri=FileProvider.getUriForFile(ctx, ctx.packageName + ".challenge-files", file); val intent=Intent(MediaStore.ACTION_IMAGE_CAPTURE).putExtra(MediaStore.EXTRA_OUTPUT, uri).addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION or Intent.FLAG_GRANT_READ_URI_PERMISSION); if(intent.resolveActivity(ctx.packageManager)==null){ promise.reject("CAMERA_UNAVAILABLE","No camera application is available."); capturePromise=null; return }; activity.startActivityForResult(intent, 8845) }
 override fun onActivityResult(activity:Activity?, requestCode:Int, resultCode:Int, data:Intent?){ if(requestCode!=8845)return; val promise=capturePromise ?: return; capturePromise=null; val file=outputFile; if(resultCode!=Activity.RESULT_OK || file==null || !file.exists()){ promise.reject("IMAGE_CAPTURE_FAILED","Camera capture did not produce an image."); return }; try{ val result=ShapeAnalyzer.analyze(file.absolutePath,target,difficulty); val image=Arguments.createMap(); image.putString("uri", Uri.fromFile(file).toString()); image.putInt("width", result.getMap("diagnostics")?.getInt("imageWidth") ?: 0); image.putInt("height", result.getMap("diagnostics")?.getInt("imageHeight") ?: 0); image.putInt("rotation",0); image.putString("capturedAt", java.time.Instant.now().toString()); val response=Arguments.createMap(); response.putMap("image",image); response.putMap("result",result); file.delete(); promise.resolve(response) } catch(e:Exception){ file.delete(); promise.reject("IMAGE_PROCESSING_FAILED", e.message, e) } }
 override fun onNewIntent(intent:Intent?) {}
 override fun onRequestPermissionsResult(requestCode:Int, permissions:Array<out String>, grantResults:IntArray):Boolean{ if(requestCode!=8844)return false; permissionPromise?.resolve(status()); permissionPromise=null; return true }
 @ReactMethod fun openCameraSettings(promise:Promise){ ctx.startActivity(Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS).setData(Uri.parse("package:${ctx.packageName}")).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)); promise.resolve(null) }
 @ReactMethod fun cleanupTemporaryImages(promise:Promise){ val dir=File(ctx.cacheDir,"challenge-images"); var deleted=0; dir.listFiles()?.forEach{ if(it.isFile && it.name.startsWith("challenge-")){ if(it.delete()) deleted++ } }; promise.resolve(deleted) }
 private fun status():String = if(Build.VERSION.SDK_INT<23 || ctx.checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED) "granted" else "denied"
}
class ShapeCameraChallengePackage: com.facebook.react.ReactPackage { override fun createNativeModules(c:ReactApplicationContext)= listOf(ShapeCameraChallengeModule(c)); override fun createViewManagers(c:ReactApplicationContext)= emptyList<com.facebook.react.uimanager.ViewManager<*,*>>() }
