package com.example.offlineshapealarm.alarm
import android.app.*; import android.content.*; import android.net.Uri; import android.os.Build; import android.provider.Settings; import android.util.Log
object AlarmScheduling { const val ACTION_FIRE="com.example.offlineshapealarm.action.FIRE_ALARM"; const val EXTRA_PAYLOAD="payload"; const val EXTRA_SNOOZE="snooze"; const val SNOOZE_DELAY_MILLIS=5 * 60 * 1000L
 fun pendingIntent(context: Context, payload: AlarmPayload): PendingIntent { val i=Intent(context, AlarmReceiver::class.java).setAction(ACTION_FIRE).setPackage(context.packageName).setData(Uri.parse("shapealarm://alarm/${payload.alarmId}")).putExtra(EXTRA_PAYLOAD, payload.toJson()); return PendingIntent.getBroadcast(context, payload.requestCode, i, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE) }
 fun snoozePendingIntent(context: Context, payload: AlarmPayload): PendingIntent { val i=Intent(context, AlarmReceiver::class.java).setAction(ACTION_FIRE).setPackage(context.packageName).setData(Uri.parse("shapealarm://snooze/${payload.alarmId}")).putExtra(EXTRA_PAYLOAD, payload.toJson()).putExtra(EXTRA_SNOOZE, true); return PendingIntent.getBroadcast(context, stableRequestCode("snooze:${payload.alarmId}"), i, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE) }
 fun canScheduleExact(context: Context): Boolean { val am=context.getSystemService(AlarmManager::class.java); return Build.VERSION.SDK_INT < 31 || am.canScheduleExactAlarms() }
 fun schedule(context: Context, payload: AlarmPayload, persist: Boolean=true) { payload.validate(); if(!canScheduleExact(context)) throw IllegalStateException("Exact alarm permission is required"); createAlarmChannel(context); val am=context.getSystemService(AlarmManager::class.java); val pi=pendingIntent(context,payload); am.cancel(pi); val show=alarmActivityIntent(context,payload); am.setAlarmClock(AlarmManager.AlarmClockInfo(payload.triggerAtEpochMillis, show), pi); if(persist) AlarmRegistry(context).upsert(payload); Log.d("ShapeAlarm","Alarm scheduled ${payload.alarmId} at ${payload.triggerAtEpochMillis}") }
 fun snooze(context: Context, payload: AlarmPayload, delayMillis: Long=SNOOZE_DELAY_MILLIS) { require(delayMillis > 0); if(!canScheduleExact(context)) throw IllegalStateException("Exact alarm permission is required"); val snoozed=payload.copy(triggerAtEpochMillis=System.currentTimeMillis()+delayMillis); val am=context.getSystemService(AlarmManager::class.java); val pi=snoozePendingIntent(context,snoozed); am.cancel(pi); if(Build.VERSION.SDK_INT>=23) am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,snoozed.triggerAtEpochMillis,pi) else am.setExact(AlarmManager.RTC_WAKEUP,snoozed.triggerAtEpochMillis,pi); SnoozeRegistry(context).upsert(snoozed); Log.d("ShapeAlarm","Alarm snoozed ${payload.alarmId} until ${snoozed.triggerAtEpochMillis}") }
 fun cancel(context: Context, id: String) { val existing=AlarmRegistry(context).get(id) ?: SnoozeRegistry(context).all().firstOrNull{it.alarmId==id} ?: AlarmPayload(id,"Alarm",1,0,0, emptyList(), true,"default","shape-photo"); val am=context.getSystemService(AlarmManager::class.java); am.cancel(pendingIntent(context, existing)); am.cancel(snoozePendingIntent(context, existing)); AlarmRegistry(context).remove(id); SnoozeRegistry(context).remove(id); Log.d("ShapeAlarm","Alarm cancelled $id") }
 fun openExactSettings(context: Context){ val i=Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK).setData(Uri.parse("package:${context.packageName}")); context.startActivity(i) }
}
