package com.example.offlineshapealarm.alarm
import android.app.*; import android.content.*; import android.media.*; import android.os.*; import android.provider.Settings; import android.util.Log
sealed class AlarmServiceState { data object Idle: AlarmServiceState(); data class Ringing(val alarmId:String): AlarmServiceState(); data class Stopping(val alarmId:String): AlarmServiceState() }
class AlarmForegroundService: Service(){ private var player: MediaPlayer?=null; private var vibrator: Vibrator?=null; private var focus: AudioFocusRequest?=null; private var state: AlarmServiceState=AlarmServiceState.Idle
 override fun onBind(intent: Intent?)=null
 override fun onStartCommand(intent: Intent?, flags:Int, startId:Int): Int { when(intent?.action){ ACTION_START_ALARM -> startAlarm(AlarmPayload.fromJson(intent.getStringExtra(AlarmScheduling.EXTRA_PAYLOAD) ?: return START_NOT_STICKY)); ACTION_STOP_ALARM, ACTION_FORCE_STOP_ALARM -> stopAlarm(intent.getStringExtra("alarmId"), intent.getStringExtra("reason") ?: "challenge-complete") }; return START_REDELIVER_INTENT }
 private fun startAlarm(payload: AlarmPayload){ if((state as? AlarmServiceState.Ringing)?.alarmId==payload.alarmId){ Log.d("ShapeAlarm","Duplicate alarm ignored ${payload.alarmId}"); return }; state=AlarmServiceState.Ringing(payload.alarmId); ActiveAlarmStore(this).ringing(payload); startForeground(NOTIFICATION_ID, activeNotification(this,payload)); startAudio(); if(payload.vibrationEnabled) startVibration(); Log.d("ShapeAlarm","Foreground service started ${payload.alarmId}") }
 private fun startAudio(){ stopAudio(); val am=getSystemService(AudioManager::class.java); if(Build.VERSION.SDK_INT>=26){ focus=AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT).setAudioAttributes(AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build()).build(); am.requestAudioFocus(focus!!) } else @Suppress("DEPRECATION") am.requestAudioFocus(null, AudioManager.STREAM_ALARM, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT); player=MediaPlayer.create(this, Settings.System.DEFAULT_ALARM_ALERT_URI)?.apply{ isLooping=true; setAudioAttributes(AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build()); start() } }
 private fun startVibration(){ vibrator=getSystemService(Vibrator::class.java); val pattern=longArrayOf(0,800,500,800,1000); if(Build.VERSION.SDK_INT>=26) vibrator?.vibrate(VibrationEffect.createWaveform(pattern,0)) else @Suppress("DEPRECATION") vibrator?.vibrate(pattern,0) }
 private fun stopAudio(){ player?.stop(); player?.release(); player=null; focus?.let{ if(Build.VERSION.SDK_INT>=26) getSystemService(AudioManager::class.java).abandonAudioFocusRequest(it) }; focus=null }
 private fun stopAlarm(requestedId:String?, reason:String){ val active=ActiveAlarmStore(this).current(); val activeId=(state as? AlarmServiceState.Ringing)?.alarmId ?: active?.optString("alarmId")?.takeIf{it.isNotBlank()}; if(requestedId!=null && activeId!=null && requestedId!=activeId){ Log.w("ShapeAlarm","Ignoring stop for $requestedId while $activeId is active"); return }; val alarmId=activeId ?: requestedId; if(activeId!=null) ActiveAlarmStore(this).dismissed(activeId,reason); state=AlarmServiceState.Stopping(alarmId ?: "unknown"); stopAudio(); vibrator?.cancel(); vibrator=null; stopForeground(STOP_FOREGROUND_REMOVE); stopSelf(); state=AlarmServiceState.Idle; Log.d("ShapeAlarm","Foreground service stopped $alarmId reason=$reason") }
 override fun onDestroy(){ stopAudio(); vibrator?.cancel(); super.onDestroy() }
 companion object { const val ACTION_START_ALARM="com.example.offlineshapealarm.action.START_ALARM"; const val ACTION_STOP_ALARM="com.example.offlineshapealarm.action.STOP_ALARM"; const val ACTION_FORCE_STOP_ALARM="com.example.offlineshapealarm.action.FORCE_STOP_ALARM" }
}
