package com.example.offlineshapealarm.alarm
import android.app.*; import android.content.*; import android.net.Uri; import android.os.Build; import android.provider.Settings; import android.util.Log
object AlarmScheduling { const val ACTION_FIRE="com.example.offlineshapealarm.action.FIRE_ALARM"; const val EXTRA_PAYLOAD="payload"
 fun pendingIntent(context: Context, payload: AlarmPayload): PendingIntent { val i=Intent(context, AlarmReceiver::class.java).setAction(ACTION_FIRE).setPackage(context.packageName).setData(Uri.parse("shapealarm://alarm/${payload.alarmId}")).putExtra(EXTRA_PAYLOAD, payload.toJson()); return PendingIntent.getBroadcast(context, payload.requestCode, i, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE) }
 fun canScheduleExact(context: Context): Boolean { val am=context.getSystemService(AlarmManager::class.java); return Build.VERSION.SDK_INT < 31 || am.canScheduleExactAlarms() }
 fun schedule(context: Context, payload: AlarmPayload, persist: Boolean=true) { payload.validate(); if(!canScheduleExact(context)) throw IllegalStateException("Exact alarm permission is required"); createAlarmChannel(context); val am=context.getSystemService(AlarmManager::class.java); val pi=pendingIntent(context,payload); am.cancel(pi); val show=alarmActivityIntent(context,payload); am.setAlarmClock(AlarmManager.AlarmClockInfo(payload.triggerAtEpochMillis, show), pi); if(persist) AlarmRegistry(context).upsert(payload); Log.d("ShapeAlarm","Alarm scheduled ${payload.alarmId} at ${payload.triggerAtEpochMillis}") }
 fun cancel(context: Context, id: String) { val existing=AlarmRegistry(context).get(id) ?: AlarmPayload(id,"Alarm",1,0,0, emptyList(), true,"default","shape-photo"); context.getSystemService(AlarmManager::class.java).cancel(pendingIntent(context, existing)); AlarmRegistry(context).remove(id); Log.d("ShapeAlarm","Alarm cancelled $id") }
 fun openExactSettings(context: Context){ val i=Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK).setData(Uri.parse("package:${context.packageName}")); context.startActivity(i) }
}
