package com.example.offlineshapealarm.alarm
import android.Manifest; import android.content.*; import android.content.pm.PackageManager; import android.os.Build; import android.provider.Settings; import com.facebook.react.bridge.*; import com.facebook.react.modules.core.PermissionAwareActivity; import com.facebook.react.modules.core.PermissionListener
class ShapeAlarmSchedulerModule(private val ctx: ReactApplicationContext): ReactContextBaseJavaModule(ctx), PermissionListener { private var permissionPromise: Promise?=null; override fun getName()="ShapeAlarmScheduler"
 @ReactMethod fun scheduleAlarm(map: ReadableMap, promise: Promise){ try{ val days=map.getArray("repeatDays"); val payload=AlarmPayload(map.getString("alarmId")!!, map.getString("label") ?: "Alarm", map.getDouble("triggerAtEpochMillis").toLong(), map.getInt("hour"), map.getInt("minute"), (0 until (days?.size() ?: 0)).map{days!!.getString(it)!!}, map.getBoolean("vibrationEnabled"), map.getString("soundId") ?: "default", map.getString("challengeType") ?: "shape-photo"); AlarmScheduling.schedule(ctx,payload,true); promise.resolve(null) } catch(e: Exception){ promise.reject("ALARM_SCHEDULE_FAILED", e.message, e) } }
 @ReactMethod fun cancelAlarm(id:String,promise:Promise){ runCatching{ AlarmScheduling.cancel(ctx,id) }.fold({promise.resolve(null)},{promise.reject("ALARM_CANCEL_FAILED",it.message,it)}) }
 @ReactMethod fun cancelAllAlarms(promise:Promise){ AlarmRegistry(ctx).all().forEach{ AlarmScheduling.cancel(ctx,it.alarmId) }; promise.resolve(null) }
 @ReactMethod fun getAlarmPermissionStatus(promise:Promise){ promise.resolve(status()) }
 @ReactMethod fun requestNotificationPermission(promise:Promise){ if(Build.VERSION.SDK_INT<33){ promise.resolve(status()); return }; val a=currentActivity as? PermissionAwareActivity ?: run{ promise.resolve(status()); return }; permissionPromise=promise; a.requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS),9919,this) }
 override fun onRequestPermissionsResult(requestCode:Int, permissions:Array<out String>, grantResults:IntArray):Boolean{ if(requestCode!=9919)return false; permissionPromise?.resolve(status()); permissionPromise=null; return true }
 @ReactMethod fun openExactAlarmSettings(promise:Promise){ runCatching{ AlarmScheduling.openExactSettings(ctx) }.fold({promise.resolve(null)},{promise.reject("OPEN_EXACT_ALARM_SETTINGS_FAILED",it.message,it)}) }
 @ReactMethod fun openNotificationSettings(promise:Promise){ val i=Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,ctx.packageName).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK); ctx.startActivity(i); promise.resolve(null) }
 @ReactMethod fun getActiveAlarm(promise:Promise){ promise.resolve(ActiveAlarmStore(ctx).current()?.let{ Arguments.fromBundle(android.os.Bundle().apply{ putString("alarmId", it.getString("alarmId")); putString("label", it.getString("label")); putString("triggeredAt", it.getString("triggeredAt")); putString("status", it.getString("status")) }) }) }
 @ReactMethod fun getScheduledAlarms(promise:Promise){ val arr=Arguments.createArray(); AlarmRegistry(ctx).all().forEach{ val m=Arguments.createMap(); m.putString("alarmId",it.alarmId); m.putString("label",it.label); m.putDouble("triggerAtEpochMillis",it.triggerAtEpochMillis.toDouble()); m.putInt("hour",it.hour); m.putInt("minute",it.minute); val d=Arguments.createArray(); it.repeatDays.forEach(d::pushString); m.putArray("repeatDays",d); m.putBoolean("vibrationEnabled",it.vibrationEnabled); m.putString("soundId",it.soundId); m.putString("challengeType",it.challengeType); m.putInt("requestCode",it.requestCode); arr.pushMap(m) }; promise.resolve(arr) }
 @ReactMethod fun stopActiveAlarm(id:String, reason:String, promise:Promise){ ctx.startService(Intent(ctx, AlarmForegroundService::class.java).setAction(AlarmForegroundService.ACTION_STOP_ALARM).putExtra("alarmId",id).putExtra("reason",reason)); promise.resolve(null) }
 private fun status(): WritableMap { val m=Arguments.createMap(); m.putString("exactAlarm", if(Build.VERSION.SDK_INT<31) "not-required" else if(AlarmScheduling.canScheduleExact(ctx)) "granted" else "denied"); m.putString("notifications", if(Build.VERSION.SDK_INT<33) "not-required" else if(ctx.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED) "granted" else "denied"); m.putString("fullScreenIntent","available"); return m }
}
class ShapeAlarmSchedulerPackage: com.facebook.react.ReactPackage { override fun createNativeModules(c:ReactApplicationContext)= listOf(ShapeAlarmSchedulerModule(c)); override fun createViewManagers(c:ReactApplicationContext)= emptyList<com.facebook.react.uimanager.ViewManager<*,*>>() }
