import { alarmSchema, type Alarm, type AlarmDraft } from "../domain/alarm";
import type { AlarmRepository } from "../domain/alarmRepository";
import { AlarmSchedulingError, ExactAlarmPermissionError, NotificationPermissionError, type AlarmScheduler } from "@/platform/alarmScheduler";
const now = () => new Date().toISOString();
const id = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`;
export class AlarmUseCases {
  constructor(private readonly repository: AlarmRepository, private readonly scheduler?: AlarmScheduler) {}
  list = () => this.repository.getAll(); get = (alarmId: string) => this.repository.getById(alarmId);
  private async ensureSchedulingPermissions() { if (!this.scheduler) return; const status = await this.scheduler.getPermissionStatus(); if (status.exactAlarm === "denied") throw new ExactAlarmPermissionError(); if (status.notifications === "denied" && (await this.scheduler.requestPermissions()).notifications === "denied") throw new NotificationPermissionError(); }
  private async restoreSchedule(alarm: Alarm) { if (!alarm.enabled || !this.scheduler) return; try { await this.scheduler.schedule(alarm); } catch (error) { console.error("Could not restore an alarm schedule after a storage failure.", error); } }
  async create(draft: AlarmDraft): Promise<Alarm> { const timestamp = now(); const alarm = alarmSchema.parse({ ...draft, label: draft.label.trim(), id: id(), createdAt: timestamp, updatedAt: timestamp }); if (alarm.enabled) await this.ensureSchedulingPermissions(); await this.repository.create(alarm); if (alarm.enabled && this.scheduler) { try { await this.scheduler.schedule(alarm); } catch (error) { await this.repository.setEnabled(alarm.id, false); throw new AlarmSchedulingError(alarm.id, error); } } return alarm; }
  async update(id: string, draft: AlarmDraft): Promise<Alarm> { const existing = await this.repository.getById(id); if (!existing) throw new Error("Alarm not found."); const alarm = alarmSchema.parse({ ...draft, label: draft.label.trim(), id, createdAt: existing.createdAt, updatedAt: now() }); if (alarm.enabled) await this.ensureSchedulingPermissions(); if (this.scheduler) await this.scheduler.cancel(id); try { await this.repository.update(alarm); } catch (error) { await this.restoreSchedule(existing); throw error; } if (alarm.enabled && this.scheduler) { try { await this.scheduler.schedule(alarm); } catch (error) { await this.repository.setEnabled(alarm.id, false); throw new AlarmSchedulingError(alarm.id, error); } } return alarm; }
  async delete(id: string) { if (this.scheduler) await this.scheduler.cancel(id); await this.repository.delete(id); }
  async toggle(id: string, enabled: boolean) { const alarm = await this.repository.getById(id); if (!alarm) throw new Error("Alarm not found."); if (enabled) await this.ensureSchedulingPermissions(); if (!enabled && this.scheduler) await this.scheduler.cancel(id); try { await this.repository.setEnabled(id, enabled); } catch (error) { if (!enabled) await this.restoreSchedule(alarm); throw error; } if (enabled && this.scheduler) { const updated = await this.repository.getById(id); if (updated) { try { await this.scheduler.schedule(updated); } catch (error) { await this.repository.setEnabled(id, false); throw new AlarmSchedulingError(id, error); } } } }
}
