import { describe, expect, it } from "vitest";
import { AlarmUseCases } from "./alarmUseCases";
import type { Alarm } from "../domain/alarm";
import type { AlarmRepository } from "../domain/alarmRepository";
import { AlarmSchedulingError, ExactAlarmPermissionError, NotificationPermissionError, type AlarmScheduler } from "@/platform/alarmScheduler";

class MemoryAlarmRepository implements AlarmRepository {
  private items = new Map<string, Alarm>();
  getAll = async () => [...this.items.values()];
  getById = async (id: string) => this.items.get(id) ?? null;
  create = async (alarm: Alarm) => { if (this.items.has(alarm.id)) throw new Error("Duplicate ID"); this.items.set(alarm.id, alarm); };
  update = async (alarm: Alarm) => { if (!this.items.has(alarm.id)) throw new Error("Not found"); this.items.set(alarm.id, alarm); };
  delete = async (id: string) => { if (!this.items.delete(id)) throw new Error("Not found"); };
  setEnabled = async (id: string, enabled: boolean) => { const alarm = this.items.get(id); if (!alarm) throw new Error("Not found"); this.items.set(id, { ...alarm, enabled }); };
}
const draft = { label: " Wake ", hour: 7, minute: 30, enabled: true, repeatDays: [], vibrationEnabled: true, challengeType: "shape-photo" as const, challengeDifficulty: "normal" as const, targetShapeId: "circle" };
const deniedScheduler: AlarmScheduler = { schedule: async () => undefined, cancel: async () => undefined, rescheduleAll: async () => undefined, requestPermissions: async () => ({ exactAlarm: "denied", notifications: "granted", fullScreenIntent: "available" }), getPermissionStatus: async () => ({ exactAlarm: "denied", notifications: "granted", fullScreenIntent: "available" }) };
const notificationDeniedScheduler: AlarmScheduler = { schedule: async () => undefined, cancel: async () => undefined, rescheduleAll: async () => undefined, requestPermissions: async () => ({ exactAlarm: "granted", notifications: "denied", fullScreenIntent: "available" }), getPermissionStatus: async () => ({ exactAlarm: "granted", notifications: "denied", fullScreenIntent: "available" }) };
const scheduleFails: AlarmScheduler = { schedule: async () => { throw new Error("native scheduler failed"); }, cancel: async () => undefined, rescheduleAll: async () => undefined, requestPermissions: async () => ({ exactAlarm: "granted", notifications: "granted", fullScreenIntent: "available" }), getPermissionStatus: async () => ({ exactAlarm: "granted", notifications: "granted", fullScreenIntent: "available" }) };
describe("alarm use cases", () => {
  it("creates a trimmed alarm", async () => { const alarms = new AlarmUseCases(new MemoryAlarmRepository()); const created = await alarms.create(draft); expect(created.label).toBe("Wake"); expect(created.id).not.toBe(""); });
  it("updates an existing alarm and its timestamp", async () => { const alarms = new AlarmUseCases(new MemoryAlarmRepository()); const created = await alarms.create(draft); const updated = await alarms.update(created.id, { ...draft, label: "Changed", minute: 45 }); expect(updated.label).toBe("Changed"); expect(updated.minute).toBe(45); expect(updated.createdAt).toBe(created.createdAt); });
  it("toggles and deletes an alarm", async () => { const repo = new MemoryAlarmRepository(); const alarms = new AlarmUseCases(repo); const created = await alarms.create(draft); await alarms.toggle(created.id, false); expect((await alarms.get(created.id))?.enabled).toBe(false); await alarms.delete(created.id); expect(await alarms.get(created.id)).toBeNull(); });
  it("does not create an alarm before exact access is granted", async () => { const repo = new MemoryAlarmRepository(); const alarms = new AlarmUseCases(repo, deniedScheduler); await expect(alarms.create(draft)).rejects.toBeInstanceOf(ExactAlarmPermissionError); expect(await alarms.list()).toEqual([]); });
  it("does not create an alarm before notifications are allowed", async () => { const repo = new MemoryAlarmRepository(); const alarms = new AlarmUseCases(repo, notificationDeniedScheduler); await expect(alarms.create(draft)).rejects.toBeInstanceOf(NotificationPermissionError); expect(await alarms.list()).toEqual([]); });
  it("schedules after notification permission is granted", async () => { let requested = 0; let scheduled = 0; const scheduler: AlarmScheduler = { schedule: async () => { scheduled++; }, cancel: async () => undefined, rescheduleAll: async () => undefined, requestPermissions: async () => { requested++; return { exactAlarm: "granted", notifications: "granted", fullScreenIntent: "available" }; }, getPermissionStatus: async () => ({ exactAlarm: "granted", notifications: "denied", fullScreenIntent: "available" }) }; await new AlarmUseCases(new MemoryAlarmRepository(), scheduler).create(draft); expect(requested).toBe(1); expect(scheduled).toBe(1); });
  it("disables an alarm when immediate native scheduling fails", async () => { const repo = new MemoryAlarmRepository(); const alarms = new AlarmUseCases(repo, scheduleFails); await expect(alarms.create(draft)).rejects.toBeInstanceOf(AlarmSchedulingError); expect((await alarms.list())[0]?.enabled).toBe(false); });
  it("restores an existing schedule when editing cannot be saved", async () => { const repo = new MemoryAlarmRepository(); const scheduled: Alarm[] = []; const scheduler: AlarmScheduler = { schedule: async (alarm) => { scheduled.push(alarm); }, cancel: async () => undefined, rescheduleAll: async () => undefined, requestPermissions: async () => ({ exactAlarm: "granted", notifications: "granted", fullScreenIntent: "available" }), getPermissionStatus: async () => ({ exactAlarm: "granted", notifications: "granted", fullScreenIntent: "available" }) }; const alarms = new AlarmUseCases(repo, scheduler); const created = await alarms.create(draft); repo.update = async () => { throw new Error("storage failed"); }; await expect(alarms.update(created.id, { ...draft, label: "Changed" })).rejects.toThrow("storage failed"); expect(scheduled).toEqual([created, created]); });
  it("keeps an alarm when native cancellation fails during deletion", async () => { const repo = new MemoryAlarmRepository(); const scheduler: AlarmScheduler = { schedule: async () => undefined, cancel: async () => { throw new Error("native cancellation failed"); }, rescheduleAll: async () => undefined, requestPermissions: async () => ({ exactAlarm: "granted", notifications: "granted", fullScreenIntent: "available" }), getPermissionStatus: async () => ({ exactAlarm: "granted", notifications: "granted", fullScreenIntent: "available" }) }; const alarms = new AlarmUseCases(repo, scheduler); const created = await alarms.create(draft); await expect(alarms.delete(created.id)).rejects.toThrow("native cancellation failed"); expect(await alarms.get(created.id)).toEqual(created); });
});
