import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text } from "react-native";
import { ScreenContainer } from "@/components/ScreenContainer";
import { alarmNativeActions, NativeAlarmScheduler, type NativeScheduledAlarmRecord, type ActiveAlarmState, type AlarmPermissionStatus } from "@/platform/alarmScheduler";
import type { Alarm } from "@/features/alarms/domain/alarm";
const scheduler = new NativeAlarmScheduler();
const testAlarm = (seconds: number): Alarm => { const d = new Date(Date.now() + seconds * 1000); return { id: "dev-test-alarm", label: `Dev test ${seconds}s`, hour: d.getHours(), minute: d.getMinutes(), enabled: true, repeatDays: [], vibrationEnabled: true, challengeType: "shape-photo", challengeDifficulty: "easy", targetShapeId: "circle", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; };
export default function DevAlarm() { const [status, setStatus] = useState<AlarmPermissionStatus | null>(null); const [active, setActive] = useState<ActiveAlarmState | null>(null); const [records, setRecords] = useState<NativeScheduledAlarmRecord[]>([]); if (!__DEV__) return <ScreenContainer><Text>Development alarm tools are hidden in production builds.</Text></ScreenContainer>; const refresh = async () => { setStatus(await scheduler.getPermissionStatus()); setActive(await alarmNativeActions.getActiveAlarm()); setRecords(await alarmNativeActions.getScheduledAlarms()); }; const run = (seconds: number) => void scheduler.schedule(testAlarm(seconds)).then(refresh).catch((error) => Alert.alert("Schedule failed", String(error))); return <ScreenContainer><Pressable style={styles.button} onPress={() => run(10)}><Text style={styles.text}>Trigger in 10 seconds</Text></Pressable><Pressable style={styles.button} onPress={() => run(60)}><Text style={styles.text}>Trigger in 60 seconds</Text></Pressable><Pressable style={styles.cancel} onPress={() => void scheduler.cancel("dev-test-alarm").then(refresh)}><Text style={styles.text}>Cancel test alarm</Text></Pressable><Pressable style={styles.secondary} onPress={refresh}><Text>Refresh native state</Text></Pressable><Text>Permissions: {JSON.stringify(status)}</Text><Text>Active: {JSON.stringify(active)}</Text><Text>Registered: {JSON.stringify(records)}</Text></ScreenContainer>; }
const styles = StyleSheet.create({ button: { backgroundColor: "#1d4ed8", padding: 16, borderRadius: 10 }, cancel: { backgroundColor: "#dc2626", padding: 16, borderRadius: 10 }, secondary: { padding: 16, borderWidth: 1, borderRadius: 10 }, text: { color: "white", fontWeight: "700", textAlign: "center" } });
