import { useState } from "react";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";
import type { AppSettings } from "@/features/settings/domain/settings";
import { ScreenContainer } from "@/components/ScreenContainer";
import { useAppStore } from "@/state/appStore";
const themes: AppSettings["theme"][] = ["system", "light", "dark"];
const levels: AppSettings["defaultChallengeDifficulty"][] = ["easy", "normal", "hard"];
export default function Settings() { const stored = useAppStore((state) => state.settings); const save = useAppStore((state) => state.saveSettings); const [settings, setSettings] = useState<AppSettings>(stored ?? { defaultVibrationEnabled: true, defaultChallengeDifficulty: "normal", emergencyOverrideEnabled: false, theme: "system" }); const [message, setMessage] = useState(""); const update = <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => setSettings((current) => ({ ...current, [key]: value })); return <ScreenContainer><View style={styles.row}><Text>Default vibration</Text><Switch value={settings.defaultVibrationEnabled} onValueChange={(value) => update("defaultVibrationEnabled", value)} /></View><Text style={styles.label}>Default difficulty</Text><View style={styles.options}>{levels.map((level) => <Pressable key={level} onPress={() => update("defaultChallengeDifficulty", level)} style={[styles.option, settings.defaultChallengeDifficulty === level && styles.selected]}><Text>{level}</Text></Pressable>)}</View><Text style={styles.label}>Theme preference</Text><View style={styles.options}>{themes.map((theme) => <Pressable key={theme} onPress={() => update("theme", theme)} style={[styles.option, settings.theme === theme && styles.selected]}><Text>{theme}</Text></Pressable>)}</View><View style={styles.row}><Text>Emergency override enabled</Text><Switch value={settings.emergencyOverrideEnabled} onValueChange={(value) => update("emergencyOverrideEnabled", value)} /></View><Pressable style={styles.save} onPress={() => { void save(settings).then(() => setMessage("Settings saved locally.")).catch(() => setMessage("Could not save settings.")); }}><Text style={styles.saveText}>Save settings</Text></Pressable>{message ? <Text accessibilityRole="alert">{message}</Text> : null}</ScreenContainer>; }
const styles = StyleSheet.create({ row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 16 }, label: { fontWeight: "600", marginTop: 8 }, options: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, option: { borderWidth: 1, borderColor: "#9ca3af", borderRadius: 8, paddingVertical: 10, paddingHorizontal: 14 }, selected: { borderColor: "#1d4ed8", backgroundColor: "#dbeafe" }, save: { marginTop: 18, backgroundColor: "#1d4ed8", padding: 16, alignItems: "center", borderRadius: 10 }, saveText: { color: "white", fontWeight: "700" } });
