import { router, useLocalSearchParams } from "expo-router";
import { useRef, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/ScreenContainer";
import { useAppStore } from "@/state/appStore";
import { formatTime } from "@/utilities/format";
import { alarmNativeActions } from "@/platform/alarmScheduler";
function HoldButton({ label, seconds, onComplete }: { label: string; seconds: number; onComplete(): void }) { const [progress, setProgress] = useState(0); const timer = useRef<ReturnType<typeof setInterval> | null>(null); const started = useRef(0); const stop = () => { if (timer.current) clearInterval(timer.current); timer.current = null; setProgress(0); }; const start = () => { started.current = Date.now(); timer.current = setInterval(() => { const value = Math.min(1, (Date.now() - started.current) / (seconds * 1000)); setProgress(value); if (value >= 1) { stop(); onComplete(); } }, 50); }; return <Pressable onPressIn={start} onPressOut={stop} style={styles.start}><Text style={styles.buttonText}>{label}</Text><View style={[styles.progress, { width: `${progress * 100}%` }]} /></Pressable>; }
export default function Challenge() { const { alarmId } = useLocalSearchParams<{ alarmId: string }>(); const alarm = useAppStore((state) => state.alarms.find((item) => item.id === alarmId)); if (!alarm) return <ScreenContainer><Text>Alarm not found.</Text></ScreenContainer>; const dismiss = (reason: "long-press" | "emergency-override") => { void alarmNativeActions.stopActiveAlarm(alarm.id, reason).then(() => router.back()).catch((error) => Alert.alert("Could not stop alarm", String(error))); }; return <ScreenContainer><Text style={styles.time}>{formatTime(alarm.hour, alarm.minute)}</Text><Text style={styles.label}>{alarm.label || "Alarm"}</Text><Text>Temporary alarm challenge</Text><Text>Hold continuously for five seconds. Releasing early resets progress.</Text><HoldButton label="Hold to dismiss" seconds={5} onComplete={() => dismiss("long-press")} /><View style={styles.shape}><Text style={styles.circle}>!</Text><Text>Emergency override is for failures only and is recorded locally.</Text></View><HoldButton label="Emergency override" seconds={10} onComplete={() => dismiss("emergency-override")} /></ScreenContainer>; }
const styles = StyleSheet.create({ time: { fontSize: 48, fontWeight: "800", textAlign: "center" }, label: { fontSize: 24, textAlign: "center", marginBottom: 24 }, shape: { alignItems: "center", padding: 24, borderWidth: 1, borderColor: "#d1d5db", borderRadius: 12, gap: 8 }, circle: { fontSize: 48 }, start: { backgroundColor: "#dc2626", padding: 16, borderRadius: 10, alignItems: "center", overflow: "hidden" }, buttonText: { color: "white", fontWeight: "700" }, progress: { position: "absolute", bottom: 0, left: 0, height: 5, backgroundColor: "#facc15" } });
